### ISSUE TITLE
Make a "create server" and a "current server" section on the main page.

### ISSUE THREAD

**Issue by Trsmorales** [Trsmorales/td-pubg#15]
Play button should link to the new game page.
create server should bring up a form with:
- ZIP/GPS Coordinates of map.
- Size Dropdown (Small 1km x 1km, Med 2km x 2km and Large 4km x 4km)

form will post to somewhere in Secure (undefined right now).

**Comment by JoshBowdenConcepts** [comment]
What if I made a modal for this so we use less routes and get the same effect with a nice look?

**Comment by Trsmorales** [comment]
yeah this should be all on the existing index.pug page. If thats what you were asking. probably only play/ settings/logout should link away from that page

**Comment by JoshBowdenConcepts** [comment]
Resolved in 62d973aba0437c011e521d29781bbd94dafec73f
